# Site settings
title: KOMIKSOVÉ NOVINY
email: siro.kunden@gmail.com
description: Stránky pořadu Komiksové Noviny, který vám přináší nové informace z komiksového světa.

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "http://komiksovenoviny.cz" # the base hostname & protocol for your site
author: "Ondřej Šírek"

#rewrite
rewrite: /
#rewrite: /KomiksoveNoviny/

google_analytics: 
addthis_id: 
disqus_account: 

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  #- title: twitter
  #  url: 
  - title: facebook
    url: https://facebook.com/KomiksoveNoviny
  - title: youtube-play
    url: https://www.youtube.com/KomiksoveNoviny
  #- title: google-plus
  #  url: 
  #- title: github
  #  url: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-sitemap, jekyll-seo-tag]
# Build settings